


application:
<<<<<<< HEAD
  name: go-example
=======
  name: turbine
>>>>>>> ab98682a801b414ad08e5026070ec547843ae65a
  port: 19002

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
<<<<<<< HEAD
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://dev.discovery.shishike.com/eureka/
=======
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://dev.discovery.shishike.com/eureka/
>>>>>>> ab98682a801b414ad08e5026070ec547843ae65a
