language: go
go:
  - 1.5.4
  - 1.6.2
  - 1.7.1
install:
  - go get github.com/ArthurHlt/gominlog
  - go get github.com/tietang/go-utils
  - go get github.com/Sirupsen/logrus
  - go get gopkg.in/yaml.v2